version: "3.9"

services:
  postgres:

    image: "postgres:14-alpine"
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./database.dev.env
    ports:
      - "5532:5432"
    networks:
      - backend

  pgadmin:
    image: "dpage/pgadmin4:6.21"
    volumes:
      - ./pgadmin-init/servers.json:/pgadmin4/servers.json
      - ./pgadmin-init/pgpass:/pgpass
    env_file:
      - ./database.dev.env
    ports:
      - "5050:80"
    networks: 
      - backend

  keycloak:
    image: "quay.io/keycloak/keycloak:16.1.1"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
      - "8787:8787" # debug port
    networks:
      - backend

  app1:
    image: "dnnet/simple-keycloak-auth-app:1.0"
    build: ./simple-keycloak-auth-app
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth/realms/master
    depends_on:
      - "postgres"
      - "keycloak"
    ports:
      - "8280:80"
    networks:
      - backend

  app2:
    image: "dnnet/lib-keycloak-auth-app:1.0"
    build: ./lib-keycloak-auth-app
    environment:
      - SERVER_URL=http://keycloak:8080/auth
      - CLIENT_ID=lib-keycloak-app
      - CLIENT_SECRET=B6gkERlZwXqKNQBzXcsCOPOslan3zpsN
      - CLIENT_ADMIN_SECRET=me830xQwyHUHoTgZSZlwtBWdQlaTj019
      - REALM=lib-keycloak-app
      - CALLBACK_URI=http://localhost:8281/callback
    depends_on:
      - "postgres"
      - "keycloak"
    ports:
      - "8281:80"
    networks:
      - backend


networks:
  backend:
    name: backend
    driver: bridge

volumes:
  postgres:
